### ISSUE TITLE
1.4.x build is broken, kitalpha repo moved

### ISSUE THREAD

**Issue by felixdo** [eclipse/capella#2210]
Please fix the repo reference in
https://github.com/eclipse/capella/blob/96c749c991046ff1b0a514c3c6a723b351ba5fd8/releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform#L63

Please don't use such unstable references in release tags.

**Comment by pdulth** [comment]
Hi Felix, 

Indeed the stable 'to-be-the-official-release' is always builded while other cots are still in stable process and once the capella stable release has been qualified, which can take several weeks, this stable is tagged as official release, and we don't want/can't rebuild a new product with new date qualifiers nor have another commitId refering to another commit than the official one when cots are made available.
 
cots promotion to official release depend also on their own lifecycle, and can be officially released after capella is released.
e.g, Sirius stable will be marked as official when the next eclipse is made official, as they follow the eclipse release train.

One possible thing might be to avoid the tpd being located on eclipse/capella repository and maintained in a separate repo with .setup, .tpd and composite site with all addons for each releases, 1.4.0 to 1.4.2 / 5.0 and 5.1. 

As we will now maintain Kitalpha, EGF and diffmerge, hopefully the process of releases shall be easier from now and we need to think to all of this.
If you really need it, can you commit for 1.4.x to refer to official kitalpha release as its highly probable that there will have no 1.4.3 ? For 5.1, it shall still work.
Thanks,

**Comment by felixdo** [comment]
And, why not mirror these unstable URLs all together into a local "capella-dependencies" repository that can be kept forever?

**Comment by felixdo** [comment]
I don't remember, how do you build your own addons? Do you not have the same problem there?

**Comment by pdulth** [comment]
Yes same issue for our addons, but we don't build 1.4.x ones since stable have been deleted. I think we probably have a 1.4.x addon in upcoming next month.

> 
> And, why not mirror these unstable URLs all together into a local "capella-dependencies" repository that can be kept forever?

Yes or no, capella depends on official releases of cots, not yet published while build, but they will become releases, so a mirror is not really needed

But yes target platform are badly managed now. 
They are wrongly promoted to download.eclipse/capella/xx/targets which shall not never had be the case, 
And the one stored in github/eclipse/capella in the official tag is not the reference neither.
What is working now is to refer to the latest tpd of the branch, which shall be uptodate (but which is not in the 1.4.x branch, but it should)
