### ISSUE TITLE
[Semantic Browser] Double Click on "Element of Interest for Diagram" content

### ISSUE THREAD

**Issue by arnauddieumegard** [eclipse/capella#2452]
Double Click on the "Element of Interest for Diagram" entry in the Semantic browser does not open the referenced diagram (it actually opens the diagram descriptor properties dialog).
Ensure that it opens the diagram.

**Comment by etraisnel2** [comment]
The issue is a little bit more general actually.
Double-click on Representation is only properly handled in the "Current Element" viewer, as the implementation ALWAYS process this viewer selection, clicking on a representation in "Referencing Element" or "Referenced Element" will always ends up in opening the wizard
